# Generated by Django 3.1.7 on 2021-03-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='İsim')),
                ('surname', models.CharField(max_length=25, verbose_name='Soyisim')),
                ('schoolId', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('classId', models.CharField(max_length=20)),
            ],
        ),
    ]
